jQuery(document).ready(function () {
var content = '<div style="z-index:1000;margin-left: 10px;"><a style="padding:10px; border-radius:5px; background:#FFFFFF; color:#0000CC; display: inline-block; text-align:center;" href="questions/index.html">Theory Questions </a><a style="padding:10px; border-radius:5px; background:#FFFFFF; color:#0000CC; display: inline-block; text-align:center;position: relative;margin-left: 20px;" href="electrical-engineering-objective-questions-mcq/index.html">MCQ Questions </a></div>';
content += '<ul id="menu-main-menu" class="menu">';
content += '<input id="input" style="padding:10px;" value="Search" />';
content += '<li class="sub menu-item"><a class="list"  href="#">BASIC ELECTRICAL</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="electrical-engineering-and-technology/index.html">Electrical Engineering & Technology</a></li>';
        content += '<li class="menu-item"><a href="atomic-structure/index.html">Atomic Structure</a></li>';
        content += '<li class="menu-item"><a href="nature-of-electricity/index.html">Nature of Electricity</a></li>';
        content += '<li class="menu-item"><a href="drift-velocity-drift-current-and-electron-mobility/index.html">Drift Velocity & Electron Mobility</a></li>';
        content += '<li class="menu-item"><a href="electric-current-and-theory-of-electricity/index.html">Electric Current </a></li>';
        content += '<li class="menu-item"><a href="static-electric-field/index.html">Static Electric Field</a></li>';
        content += '<li class="menu-item"><a href="what-is-magnetic-field/index.html">Magnetic Field</a></li>';
        content += '<li class="menu-item"><a href="electrical-conductivity-of-metal-semiconductor-and-insulator/index.html">Electrical Conductance and Conductivity</a></li>';
        content += '<li class="menu-item"><a href="electrical-resistance-and-laws-of-resistance/index.html">Electrical Resistance and Resistivity</a></li>';
        content += '<li class="menu-item"><a href="types-of-resistor-carbon-composition-and-wire-wound-resistor/index.html">Resistor</a></li>';
        content += '<li class="menu-item"><a href="resistances-in-series-and-resistances-in-parallel/index.html">Resistances in Series and Parallel</a></li>';
        content += '<li class="menu-item"><a href="voltage-or-electric-potential-difference/index.html">Theory of Electrical Potential</a></li>';
        content += '<li class="menu-item"><a href="what-is-capacitor-and-what-is-dielectric/index.html">What is Capacitor and Capacitance?</a></li>';
        content += '<li class="menu-item"><a href="what-is-inductor-and-inductance-theory-of-inductor/index.html">What is Inductor and Inductance?</a></li>';
        content += '<li class="menu-item"><a href="ionization-process-and-definition/index.html">Ionization Process </a></li>';
        content += '<li class="menu-item"><a href="electric-power-single-and-three-phase/index.html">Electrical Power</a></li>';
        content += '<li class="menu-item"><a href="electric-lamp-types-of-electric-lamp/index.html">Electric Lamps</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">CIRCUIT THEORY</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="electrical-dc-series-and-parallel-circuit/index.html">Electrical DC Circuit</a></li>';
        content += '<li class="menu-item"><a href="ideal-dependent-independent-voltage-current-source/index.html">Voltage and Current Source</a></li>';
        content += '<li class="menu-item"><a href="single-and-multi-mesh-analysis/index.html">Mesh Network and Analysis</a></li>';
        content += '<li class="menu-item"><a href="superposition-theorem/index.html">Superposition Theorem</a></li>';
        content += '<li class="menu-item"><a href="thevenin-theorem-and-thevenin-equivalent-voltage-and-resistance/index.html">Thevenin Theorem</a></li>';
        content += '<li class="menu-item"><a href="norton-theorem-norton-equivalent-current-and-resistance/index.html">Norton Theorem</a></li>';
        content += '<li class="menu-item"><a href="maximum-power-transfer-theorem/index.html">Maximum Power Transfer Theorem</a></li>';
        content += '<li class="menu-item"><a href="reciprocity-theorem/index.html">Reciprocity Theorem</a></li>';
        content += '<li class="menu-item"><a href="compensation-theorem/index.html">Compensation Theorem</a></li>';
        content += '<li class="menu-item"><a href="tellegen-theorem/index.html">Tellegen Theorem</a></li>';
        content += '<li class="menu-item"><a href="voltage-divider/index.html">Voltage Divider</a></li>';
        content += '<li class="menu-item"><a href="three-phase-circuit-star-and-delta-system/index.html">Three Phase System</a></li>';
        content += '<li class="menu-item"><a href="delta-star-transformation-star-delta-transformation/index.html">Star - Delta Transformation</a></li>';
        content += '<li class="menu-item"><a href="rl-circuit-transfer-function-time-constant-rl-circuit-as-filter/index.html">RL Circuit</a></li>';
        content += '<li class="menu-item"><a href="rl-series-circuit/index.html">RL Series Circuit</a></li>';
        content += '<li class="menu-item"><a href="rl-parallel-circuit/index.html">RL Parallel Circuit</a></li>';
        content += '<li class="menu-item"><a href="rlc-circuit/index.html">RLC Circuit</a></li>';
        content += '<li class="menu-item"><a href="series-rlc-circuit/index.html">Series RLC Circuit</a></li>';
        content += '<li class="menu-item"><a href="rlc-parallel-circuit/index.html">Parallel RLC Circuit</a></li>';
        content += '<li class="menu-item"><a href="resonance-in-series-rlc-circuit/index.html">Resonance in Series RLC Circuit</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">ELECTRICAL LAWS</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="ohms-law-equation-formula-and-limitation-of-ohms-law/index.html">Ohm\'s Law</a></li>';
        content += '<li class="menu-item"><a href="coulombs-law/index.html">Coulomb\'s Law</a></li>';
        content += '<li class="menu-item"><a href="kirchhoff-current-law-and-kirchhoff-voltage-law/index.html">Kirchhoff\'s Current and Voltage Law</a></li>';
        content += '<li class="menu-item"><a href="joules-law/index.html">Joule\'s Law</a></li>';
        content += '<li class="menu-item"><a href="gausss-theorem/index.html">Gauss\'s Theorem</a></li>';
        content += '<li class="menu-item"><a href="fleming-left-hand-rule-and-fleming-right-hand-rule/index.html">Fleming Left and Right Hand Rule</a></li>';
        content += '<li class="menu-item"><a href="faraday-law-of-electromagnetic-induction/index.html">Faraday Law of Electromagnetic Induction</a></li>';
        content += '<li class="menu-item"><a href="lenz-law-of-electromagnetic-induction/index.html">Lenz Law of Electromagnetic Induction</a></li>';
        content += '<li class="menu-item"><a href="seebeck-effect-and-seebeck-coefficient/index.html">Seebeck Effect and Seebeck Coefficient</a></li>';
        content += '<li class="menu-item"><a href="biot-savart-law/index.html">Biot Savart Law</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">BATTERY</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="battery-history-and-working-principle-of-batteries/index.html">History and Working Principle of Batteries</a></li>';
        content += '<li class="menu-item"><a href="charging-of-battery-and-discharging-of-battery/index.html">Charging and Discharging of Battery</a></li>';
        content += '<li class="menu-item"><a href="principle-of-electrolysis-of-copper-sulfate-electrolyte/index.html">Principle of Electrolysis</a></li>';
        content += '<li class="menu-item"><a href="faradays-first-and-second-laws-of-electrolysis/index.html">Faraday Laws of Electrolysis</a></li>';
        content += '<li class="menu-item"><a href="applications-of-electrolysis-electroplating-electroforming-electrorefining/index.html">Applications of Electrolysis</a></li>';
        content += '<li class="menu-item"><a href="working-of-lead-acid-battery-lead-acid-secondary-storage-battery/index.html">Working of Lead Acid Battery</a></li>';
        content += '<li class="menu-item"><a href="voltaic-cell/index.html">Voltaic Cell</a></li>';
        content += '<li class="menu-item"><a href="alkaline-batteries/index.html">Alkaline Batteries</a></li>';
        content += '<li class="menu-item"><a href="nickel-iron-batteries-or-edison-batteries/index.html">Nickel Iron Batteries or Edison Batteries</a></li>';
        content += '<li class="menu-item"><a href="zinc-carbon-battery/index.html">Zinc-Carbon Battery</a></li>';
        content += '<li class="menu-item"><a href="construction-of-zinc-carbon-battery-leclanche-cell/index.html">Construction of Leclanche Cell</a></li>';
        content += '<li class="menu-item"><a href="magnesium-battery-chemistry-construction-of-magnesium-battery/index.html">Magnesium Battery</a></li>';
        content += '<li class="menu-item"><a href="aluminum-air-battery/index.html">Aluminum Air Battery</a></li>';
        content += '<li class="menu-item"><a href="mercuric-oxide-battery-chemistry-construction-advantages-uses/index.html">Mercuric Oxide Battery</a></li>';
        content += '<li class="menu-item"><a href="series-parallel-battery-cells/index.html">Series Parallel Battery Cells</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">OTHERS</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="si-system-of-units/index.html">SI System of Units</a></li>';
        content += '<li class="menu-item"><a href="potentiometer-working-principle-of-potentiometer/index.html">Working Principle of Potentiometer</a></li>';
        content += '<li class="menu-item"><a href="laplace-transformation/index.html">Laplace Transforms</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">TRANSFORMER</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="electrical-power-transformer-definition-and-types-of-transformer/index.html">Electrical Power Transformer </a></li>';
        content += '<li class="menu-item"><a href="what-is-transformer-definition-working-principle-of-transformer/index.html">Working Principle of Transformer</a></li>';
        
        content += '<li class="menu-item"><a href="ideal-transformer/index.html">Ideal Transformer</a></li>';
        content += '<li class="menu-item"><a href="emf-equation-of-transformer-turns-voltage-transformation-ratio-of-transformer/index.html">EMF Equation of Transformer</a></li>';
        
        content += '<li class="menu-item"><a href="theory-of-transformer-on-load-and-no-load-operation/index.html">Theory of Transformer</a></li>';
        content += '<li class="menu-item"><a href="resistance-leakage-reactance-or-impedance-of-transformer/index.html">Leakage Reactance of Transformer</a></li>';
        
        content += '<li class="menu-item"><a href="equivalent-circuit-of-transformer-referred-to-primary-and-secondary/index.html">Equivalent Circuit of Transformer</a></li>';
        
        content += '<li class="menu-item"><a href="voltage-regulation-of-transformer/index.html">Voltage Regulation of Transformer </a></li>';
        
        content += '<li class="menu-item"><a href="hysteresis-eddy-current-iron-or-core-losses-and-copper-loss-in-transformer/index.html">Losses in Transformer</a></li>';
        
        content += '<li class="menu-item"><a href="open-and-short-circuit-test-on-transformer/index.html">Open and Short Circuit Test on Transformer</a></li>';
        content += '<li class="menu-item"><a href="tertiary-winding-of-transformer-three-winding-transformer/index.html">Tertiary Winding of Transformer</a></li>';
        content += '<li class="menu-item"><a href="parallel-operation-of-transformers/index.html">Parallel operation of Transformers</a></li>';
        content += '<li class="menu-item"><a href="core-of-transformer-and-design-of-transformer-core/index.html">Core of Transformer</a></li>';
        content += '<li class="menu-item"><a href="transformer-insulating-oil-and-types-of-transformer-oil/index.html">Transformer Insulating Oil</a></li>';
        
        content += '<li class="menu-item"><a href="dga-or-dissolved-gas-analysis-of-transformer-oil-furfural-or-furfuraldehyde-analysis/index.html">Dissolved Gas Analysis of Transformer Oil</a></li>';
        content += '<li class="menu-item"><a href="transformer-cooling-system-and-methods/index.html">Transformer Cooling System</a></li>';
        content += '<li class="menu-item"><a href="transformer-accessories/index.html">Transformer Accessories</a></li>';
        content += '<li class="menu-item"><a href="conservator-tank-of-transformer/index.html">• <span class="subTopic">Conservator Tank of Transformer</span></a></li>';
        content += '<li class="menu-item"><a href="buchholz-relay-in-transformer-buchholz-relay-operation-and-principle/index.html">• <span class="subTopic">Buchholz Relay in Transformer</span></a></li>';
        content += '<li class="menu-item"><a href="silica-gel-breather/index.html">• <span class="subTopic">Silica Gel Breather</span></a></li>';
        content += '<li class="menu-item"><a href="radiator-of-transformer-function-of-radiator/index.html">• <span class="subTopic">Radiator of Transformer</span></a></li>';
        content += '<li class="menu-item"><a href="magnetic-oil-gauge-or-mog-magnetic-oil-level-indicator-of-transformer/index.html">• <span class="subTopic">Magnetic Oil Gauge or MOG</span></a></li>';
        content += '<li class="menu-item"><a href="oil-winding-and-remotetemperature-indicator-of-transformer/index.html">• <span class="subTopic">Temperature Indicators of Transformer</span></a></li>';
        content += '<li class="menu-item"><a href="on-load-and-no-load-tap-changer-of-transformer-oltc-and-nltc/index.html">• <span class="subTopic">On and No Load Tap Changer</span></a></li>';
        
        content += '<li class="menu-item"><a href="what-is-auto-transformer/index.html">Auto Transformer</a></li>';
        content += '<li class="menu-item"><a href="single-three-phase-transformer-vs-bank-of-three-single-phase-transformers/index.html">Three phase transformer</a></li>';
        
        content += '<li class="menu-item"><a href="current-transformer-ct-class-ratio-error-phase-angle-error-in-current-transformer/index.html">Current Transformer</a></li>';
        
        content += '<li class="menu-item"><a href="voltage-transformer-or-potential-transformer-theory/index.html">Voltage Transformer</a></li>';
        
        content += '<li class="menu-item"><a href="accuracy-limit-factor-and-instrument-security-factor-of-current-transformer/index.html">• <span class="subTopic">Accuracy Limit & Instrument Security Factor</span></a></li>';
        
        content += '<li class="menu-item"><a href="knee-point-voltage-of-current-transformer-ps-class/index.html">• <span class="subTopic">Knee Point Voltage of Current Transformer</span></a></li>';
        
        content += '<li class="menu-item"><a href="transformer-winding-resistance-measurement/index.html">• Transformer winding resistance measurement</a></li>';
        content += '<li class="menu-item"><a href="voltage-and-turn-ratio-test-of-transformer/index.html">• Transformer Ratio Test</a></li>';
        content += '<li class="menu-item"><a href="vector-group-test-of-power-transformer/index.html">• Vector Group Test of Transformer</a></li>';
        content += '<li class="menu-item"><a href="insulation-dielectric-test-of-transformer/index.html">• Dielectric Test of Transformer</a></li>';
        content += '<li class="menu-item"><a href="transformer-oil-and-winding-temperature-rise-test/index.html">• Temperature Rise Test of Transformer</a></li>';
        content += '<li class="menu-item"><a href="impulse-test-of-transformer/index.html">• Transformer Impulse Test</a></li>';
        content += '<li class="menu-item"><a href="sweep-frequency-response-analysis-test-sfra-test/index.html">• Sweep Frequency Response Analysis</a></li>';
        content += '<li class="menu-item"><a href="tan-delta-test-loss-angle-test-dissipation-factor-test/index.html">• Tan Delta or Dissipation Factor Test</a></li>';
        content += '<li class="menu-item"><a href="over-fluxing-in-transformer/index.html">Over Fluxing in Transformer</a></li>';
        content += '<li class="menu-item"><a href="what-is-earthing-transformer-or-grounding-transformer/index.html">Earthing  or Grounding Transformer</a></li>';
        content += '<li class="menu-item"><a href="external-and-internal-faults-in-transformer/index.html">External & Internal Faults in Transformer</a></li>';
        content += '<li class="menu-item"><a href="backup-protection-of-transformer-over-current-and-earth-fault/index.html">Backup Protection of Transformer</a></li>';
        content += '<li class="menu-item"><a href="differential-protection-of-transformer-differential-relays/index.html">Differential Protection of Transformer</a></li>';
        content += '<li class="menu-item"><a href="restricted-earth-fault-protection-of-transformer-ref-protection/index.html">Restricted Earth Fault Protection</a></li>';
        content += '<li class="menu-item"><a href="maintenance-of-transformer/index.html">Maintenance of Transformer</a></li>';
        content += '<li class="menu-item"><a href="distribution-transformer-efficiency-of-distribution-transformer-all-day-efficiency/index.html">Distribution Transformer</a></li>';
        content += '<li class="menu-item"><a href="air-core-transformer/index.html">Air Core Transformer</a></li>';
        content += '<li class="menu-item"><a href="high-voltage-transformer/index.html">High Voltage Transformer</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">DC MOTOR</a>';
	content += '<ul class="sub-menu">';
    	content += '<li class="menu-item"><a href="electrical-motor-types-classification-and-history-of-motor/index.html">Electrical Motor</a></li>';
		content += '<li class="menu-item"><a href="working-of-electric-motor/index.html">Working of Electric Motor</a></li>';
        content += '<li class="menu-item"><a href="dc-motor-or-direct-current-motor/index.html">DC Motor</a></li>';
        content += '<li class="menu-item"><a href="working-or-operating-principle-of-dc-motor/index.html">Working Principle of DC Motor</a></li>';
        content += '<li class="menu-item"><a href="construction-of-dc-motor-yoke-poles-armature-field-winding-commutator-brushes-of-dc-motor/index.html">Construction of DC Motor</a></li>';
        content += '<li class="menu-item"><a href="torque-equation-of-dc-motor/index.html">Torque Equation of DC Motor</a></li>';
        content += '<li class="menu-item"><a href="types-of-dc-motor-separately-excited-shunt-series-compound-dc-motor/index.html">Types of DC Motor</a></li>';
        content += '<li class="menu-item"><a href="shunt-wound-dc-motor-dc-shunt-motor/index.html">Shunt Wound DC Motor</a></li>';
        content += '<li class="menu-item"><a href="series-wound-dc-motor-or-dc-series-motor/index.html">Series Wound DC Motor</a></li>';
        content += '<li class="menu-item"><a href="compound-wound-dc-motor-or-dc-compound-motor/index.html">Compound Wound DC Motor</a></li>';
        content += '<li class="menu-item"><a href="starting-methods-to-limit-starting-current-torque-of-dc-motor/index.html">Starting Methods of DC Motor</a></li>';
        content += '<li class="menu-item"><a href="3-point-starter-working-principle-and-construction-of-three-point-starter/index.html">Three Point Starter</a></li>';
        content += '<li class="menu-item"><a href="4-point-starter-working-principle-and-construction-of-four-point-starter/index.html">Four Point Starter</a></li>';
        content += '<li class="menu-item"><a href="speed-regulation-of-dc-motor/index.html">Speed Regulation of DC Motor</a></li>';
        content += '<li class="menu-item"><a href="speed-control-of-dc-motor/index.html">Speed Control of DC Motor</a></li>';
        content += '<li class="menu-item"><a href="lap-winding-simplex-and-duplex-lap-winding/index.html">Simplex and Duplex Lap Winding</a></li>';
        content += '<li class="menu-item"><a href="permanent-magnet-dc-motor-or-pmdc-motor/index.html">Permanent Magnet DC Motor</a></li>';
        content += '<li class="menu-item"><a href="ward-leonard-method-of-speed-control/index.html">Ward Leonard Method of Speed Control</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">INDUCTION MOTOR</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="induction-motor-types-of-induction-motor/index.html">Induction Motor </a></li>';
        content += '<li class="menu-item"><a href="working-principle-of-three-phase-induction-motor/index.html">Three Phase Induction Motor</a></li>';
        content += '<li class="menu-item"><a href="single-phase-induction-motor/index.html">Single Phase Induction Motor</a></li>';
        content += '<li class="menu-item"><a href="linear-induction-motor/index.html">Linear Induction Motor</a></li>';
        content += '<li class="menu-item"><a href="types-of-three-phase-induction-motor/index.html">Types of Three Phase Induction Motor</a></li>';
        content += '<li class="menu-item"><a href="torque-equation-of-three-phase-induction-motor/index.html">Torque Equation of Three Phase IM</a></li>';
        content += '<li class="menu-item"><a href="starting-methods-for-polyphase-induction-machine/index.html">Starting Methods for Polyphase IM</a></li>';
        content += '<li class="menu-item"><a href="speed-control-of-three-phase-induction-motor/index.html">Speed Control of Three Phase IM</a></li>';
        content += '<li class="menu-item"><a href="losses-and-efficiency-of-induction-motor/index.html">Losses and Efficiency of Induction Motor</a></li>';
        content += '<li class="menu-item"><a href="construction-of-three-phase-induction-motor/index.html">Construction of Three Phase Induction Motor</a></li>';
        content += '<li class="menu-item"><a href="types-of-single-phase-induction-motor/index.html">Types of Single Phase Induction Motor</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">SPECIAL MOTOR</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="motor-generator-set-m-g-set/index.html">Motor Generator Set</a></li>';
        content += '<li class="menu-item"><a href="servo-motor-servo-mechanism-theory-and-working-principle/index.html">Servo Motor</a></li>';
        content += '<li class="menu-item"><a href="dc-servo-motors-theory-and-working-principle/index.html">DC Servo Motors</a></li>';
        content += '<li class="menu-item"><a href="servo-motor-controller-or-servo-motor-driver/index.html">Servo Motor Controller or Driver</a></li>';
        content += '<li class="menu-item"><a href="servo-motor-applications-in-robotics-solar-tracking-system-etc/index.html">Servo Motor Applications</a></li>';
        content += '<li class="menu-item"><a href="interfacing-of-stepper-motor/index.html">Interfacing of Stepper Motor</a></li>';
        content += '<li class="menu-item"><a href="bipolar-stepper-motor/index.html">Bipolar Stepper Motor</a></li>';
        content += '<li class="menu-item"><a href="ac-series-motor/index.html">AC Series Motor</a></li>';
        content += '<li class="menu-item"><a href="phasor-diagram-for-ac-series-motor/index.html">Phasor Diagram for AC Series Motor</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">SYNCHRONOUS MOTOR</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="synchronous-motor-working-principle/index.html">Working Principle of Synchronous Motor</a></li>';
        content += '<li class="menu-item"><a href="synchronous-motor-excitation/index.html">Synchronous Motor Excitation</a></li>';
        content += '<li class="menu-item"><a href="hunting-in-synchronous-motor/index.html">Hunting in Synchronous Motor</a></li>';
        content += '<li class="menu-item"><a href="phasor-diagram-for-synchronous-motor/index.html">Phasor Diagram for Synchronous Motor</a></li>';
        content += '<li class="menu-item"><a href="derivation-of-various-power-conditions-in-alternators-and-synchronous-motors/index.html">Power Conditions in Synchronous Machine</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">GENERATOR</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="alternator-or-synchronous-generator/index.html">Alternator or Synchronous Generator</a></li>';
        content += '<li class="menu-item"><a href="working-principle-of-alternator/index.html">Working Principle of Alternator</a></li>';
        content += '<li class="menu-item"><a href="construction-of-alternator/index.html">Construction of Alternator</a></li>';
        content += '<li class="menu-item"><a href="rating-of-alternator/index.html">Rating of Alternator</a></li>';
        content += '<li class="menu-item"><a href="armature-winding-pole-pitch-coil-span-commutator-pitch/index.html">Armature Winding</a></li>';
        content += '<li class="menu-item"><a href="armature-winding-of-alternator/index.html">Armature Winding of Alternator</a></li>';
        content += '<li class="menu-item"><a href="winding-factor-pitch-factor-distribution-factor/index.html">Winding Factor</a></li>';
        content += '<li class="menu-item"><a href="armature-reaction-in-synchronous-machine-alternator/index.html">Armature Reaction of Alternator</a></li>';
        content += '<li class="menu-item"><a href="phasor-diagram-for-synchronous-generator/index.html">Phasor Diagram for Synchronous Generator</a></li>';
        content += '<li class="menu-item"><a href="induction-generator/index.html">Induction Generator</a></li>';
        content += '<li class="menu-item"><a href="principle-of-dc-generator/index.html">Working Principle of DC Generator</a></li>';
        content += '<li class="menu-item"><a href="construction-of-dc-generator-yoke-pole-armature-brushes-of-dc-generator/index.html">Construction of DC Generator</a></li>';
        content += '<li class="menu-item"><a href="commutation-in-dc-machine-or-commutation-in-dc-generator-or-motor/index.html">Commutation in DC Machine</a></li>';
        content += '<li class="menu-item"><a href="methods-of-improving-commutation/index.html">Methods of Improving Commutation</a></li>';
        content += '<li class="menu-item"><a href="frog-leg-winding-drum-winding-gramme-ring-winding/index.html">Frog Leg, Drum and Gramme Ring Winding</a></li>';
        content += '<li class="menu-item"><a href="types-of-dc-generators/index.html">Types of DC Generators</a></li>';
        content += '<li class="menu-item"><a href="magnetization-curve-of-dc-generator/index.html">Magnetization Curve of DC Generator</a></li>';
        content += '<li class="menu-item"><a href="characteristic-of-separately-excited-dc-generator/index.html">Characteristic of Separately Excited DC Gen</a></li>';
        content += '<li class="menu-item"><a href="characteristic-of-shunt-wound-dc-generator/index.html">Characteristic of DC Shunt Generator</a></li>';
        content += '<li class="menu-item"><a href="characteristic-of-series-wound-dc-generator/index.html">Characteristics of DC Series Generator</a></li>';
        content += '<li class="menu-item"><a href="characteristic-of-dc-compound-wound-generators/index.html">Characteristic of DC Compound Generators</a></li>';
        content += '<li class="menu-item"><a href="armature-reaction-in-dc-machine/index.html">Armature Reaction in DC Machine</a></li>';
        content += '<li class="menu-item"><a href="dc-generators-performance-curves/index.html">DC Generators Performance Curves</a></li>';
        content += '<li class="menu-item"><a href="applications-of-dc-generators/index.html">Applications of DC Generators</a></li>';
        content += '<li class="menu-item"><a href="testing-of-dc-machine/index.html">Testing of DC Machine</a></li>';
        content += '<li class="menu-item"><a href="swinburnes-test-of-dc-machine/index.html">Swinburne\'s Test of DC Machine</a></li>';
        content += '<li class="menu-item"><a href="hopkinsons-test/index.html">Hopkinson\'s Test</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">ELECTRIC DRIVES</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="electrical-drives/index.html">Electrical Drives</a></li>';
        content += '<li class="menu-item"><a href="dynamics-of-electrical-drives/index.html">Dynamics of Electrical Drives</a></li>';
        content += '<li class="menu-item"><a href="electric-motor-power-rating/index.html">Electric Motor Power Rating</a></li>';
        content += '<li class="menu-item"><a href="thermal-model-of-motor/index.html">Thermal Model of Motor</a></li>';
        content += '<li class="menu-item"><a href="motor-duty-class/index.html">Motor Duty Class</a></li>';
        content += '<li class="menu-item"><a href="dc-motor-drives/index.html">DC Motor Drives</a></li>';
        content += '<li class="menu-item"><a href="induction-motor-braking/index.html">Induction Motor Braking</a></li>';
        content += '<li class="menu-item"><a href="induction-motor-drives-starting-braking-speed-control-of-induction-motor/index.html">Induction Motor Drives</a></li>';
        content += '<li class="menu-item"><a href="what-is-braking-types-of-braking-regenerative-plugging-dynamic-braking/index.html">Types of Braking</a></li>';
        content += '<li class="menu-item"><a href="control-of-electrical-drives/index.html">Control of Electrical Drives</a></li>';
        content += '<li class="menu-item"><a href="synchronous-motor-drives/index.html">Synchronous Motor Drives</a></li>';
        content += '<li class="menu-item"><a href="stepper-motor-drive/index.html">Stepper Motor Drive</a></li>';
        content += '<li class="menu-item"><a href="variable-frequency-drive/index.html">Variable Frequency Drive</a></li>';
        content += '<li class="menu-item"><a href="field-oriented-control/index.html">Field Oriented Control</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">POWER SYSTEM</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="electric-power-generation/index.html">Electric Power Generation</a></li>';
        content += '<li class="menu-item"><a href="power-plants-types-of-power-plant/index.html">Power Plant</a></li>';
        content += '<li class="menu-item"><a href="thermal-power-generation-plant-or-thermal-power-station/index.html">Thermal Power Plant</a></li>';
        content += '<li class="menu-item"><a href="steam-boiler-working-principle-and-types-of-boiler/index.html">Steam Boiler</a></li>';
        content += '<li class="menu-item"><a href="fire-tube-boiler-operation-and-types-of-fire-tube-boiler/index.html">• <span class="subTopic">Fire Tube Boiler</span></a></li>';
        content += '<li class="menu-item"><a href="water-tube-boiler-operation-and-types-of-water-tube-boiler/index.html">• <span class="subTopic">Water Tube Boiler</span></a></li>';
        content += '<li class="menu-item"><a href="boiler-feed-water-treatment-process-demineralization-plant/index.html">• <span class="subTopic">Boiler Feed Water Treatment</span></a></li>';
        content += '<li class="menu-item"><a href="feed-water-and-steam-circuit-of-boiler/index.html">• <span class="subTopic">Feed Water and Steam Circuit of Boiler</span></a></li>';
        content += '<li class="menu-item"><a href="steam-boiler-furnace-grate-firebox-combustion-chamber-of-furnace/index.html">• <span class="subTopic">Steam Boiler Furnace</span></a></li>';
        content += '<li class="menu-item"><a href="coal-combustion-theory/index.html">• <span class="subTopic">Coal Combustion Theory</span></a></li>';
        content += '<li class="menu-item"><a href="methods-of-firing-steam-boiler/index.html">Methods of Firing Steam Boiler</a></li>';
        content += '<li class="menu-item"><a href="fluidized-bed-combustion-types-and-advantages-of-fluidized-bed-combustion/index.html">Fluidized Bed Combustion</a></li>';
        content += '<li class="menu-item"><a href="hydro-power-plant-construction-working-and-history-of-hydro-power-plant/index.html">Hydro Power Plant</a></li>';
        content += '<li class="menu-item"><a href="diesel-power-station/index.html">Diesel Power Station</a></li>';
        content += '<li class="menu-item"><a href="nuclear-power-station-or-nuclear-power-plant/index.html">Nuclear Power Plant</a></li>';
        content += '<li class="menu-item"><a href="cogeneration-combine-heat-and-power/index.html">Cogeneration</a></li>';
        content += '<li class="menu-item"><a href="solar-energy-system-history-of-solar-energy/index.html">Solar Energy System</a></li>';
        content += '<li class="menu-item"><a href="basic-wind-energy/index.html">Basic Wind Energy</a></li>';
        content += '<li class="menu-item"><a href="wind-turbine-working-types-and-history-of-wind-turbine/index.html">Wind Turbine</a></li>';
        content += '<li class="menu-item"><a href="theory-of-wind-turbine/index.html">Theory of Wind Turbine</a></li>';
        content += '<li class="menu-item"><a href="thermoelectric-power-generators-or-seebeck-power-generation/index.html">Thermoelectric Power Generators</a></li>';
        content += '<li class="menu-item"><a href="mhd-generation-or-magneto-hydro-dynamic-power-generation/index.html">Magneto Hydro Dynamic Power Generation</a></li>';
        content += '<li class="menu-item"><a href="economics-of-power-generation/index.html">Economics of Power Generation</a></li>';
        content += '<li class="menu-item"><a href="economiser-in-thermal-power-plant-economiser/index.html">Economiser in Thermal Power Plant</a></li>';
        content += '<li class="menu-item"><a href="steam-condenser-of-turbine/index.html">Steam Condenser of Turbine</a></li>';
        content += '<li class="menu-item"><a href="jet-condenser-low-level-high-level-ejector-jet-condenser/index.html">Jet Steam Condenser</a></li>';
        content += '<li class="menu-item"><a href="surface-steam-condenser/index.html">Surface Steam Condenser</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">TRANSMISSION</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="electrical-power-transmission-system-and-network/index.html">Electrical Power Transmission System</a></li>';
        content += '<li class="menu-item"><a href="performance-of-transmission-line/index.html">Performance of Transmission Line</a></li>';
        content += '<li class="menu-item"><a href="abcd-parameters-of-transmission-line/index.html">ABCD Parameters of Transmission Line</a></li>';
        content += '<li class="menu-item"><a href="short-transmission-line/index.html">Short Transmission Line</a></li>';
        content += '<li class="menu-item"><a href="medium-transmission-line/index.html">Medium Transmission Line</a></li>';
        content += '<li class="menu-item"><a href="long-transmission-line/index.html">Long Transmission Line</a></li>';
        content += '<li class="menu-item"><a href="power-system-stability/index.html">Power System Stability</a></li>';
        content += '<li class="menu-item"><a href="transient-stability-and-swing-equation/index.html">Transient Stability in Power System</a></li>';
        content += '<li class="menu-item"><a href="skin-effect-in-transmission-lines/index.html">Skin Effect in Transmission Lines</a></li>';
        content += '<li class="menu-item"><a href="ferranti-effect-in-power-system/index.html">Ferranti Effect in Power System</a></li>';
        content += '<li class="menu-item"><a href="capacitor-bank-reactive-power-compensation/index.html">Capacitor Bank</a></li>';
        content += '<li class="menu-item"><a href="shunt-capacitor-capacitor-bank/index.html">Shunt Capacitor</a></li>';
        content += '<li class="menu-item"><a href="corona-effect-in-power-system/index.html">Corona Effect in Power System</a></li>';
        content += '<li class="menu-item"><a href="electrical-power-substation-engineering-and-layout/index.html"> Electrical Substation</a></li>';
        content += '<li class="menu-item"><a href="mobile-substation-portable-substation-mobile-transformer/index.html"> Mobile Substation</a></li>';
        content += '<li class="menu-item"><a href="electrical-bus-system-and-electrical-substation-layout/index.html"> Electrical Bus System & Substation Layout</a></li>';
        content += '<li class="menu-item"><a href="electrical-insulator-insulating-material-porcelain-glass-polymer-insulator/index.html"> Electrical Insulator</a></li>';
        content += '<li class="menu-item"><a href="types-of-electrical-insulator-overhead-insulator/index.html"> Types of Electrical Insulator</a></li>';
        content += '<li class="menu-item"><a href="insulation-coordination-in-power-system/index.html"> Insulation Coordination</a></li>';
        content += '<li class="menu-item"><a href="electrical-insulator-testing-cause-of-insulator-failure/index.html"> Insulator Testing</a></li>';
        content += '<li class="menu-item"><a href="electrical-isolator-or-electrical-isolation-switch/index.html">Electrical Isolator or Isolation Switch</a></li>';
        content += '<li class="menu-item"><a href="electrical-transmission-tower-types-and-design/index.html">Transmission Tower </a></li>';
        content += '<li class="menu-item"><a href="methods-of-transmission-tower-erection/index.html">Transmission Tower Erection</a></li>';
        content += '<li class="menu-item"><a href="basic-concept-of-transmission-tower-foundation/index.html">Transmission Tower Foundation Concept</a></li>';
        content += '<li class="menu-item"><a href="design-of-foundations-of-transmission-towers-in-different-soils/index.html">Transmission Tower Foundation Design</a></li>';
        content += '<li class="menu-item"><a href="electrical-power-distribution-system-radial-ring-main-electrical-power-distribution-system/index.html">Distribution System</a></li>';
        content += '<li class="menu-item"><a href="electrical-power-factor/index.html">Electrical Power Factor</a></li>';
        content += '<li class="menu-item"><a href="load-curve-load-duration-curve-daily-load-curve/index.html">Load Curve</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">SWITCHGEAR</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="electrical-switchgear-protection/index.html">Electrical Switchgear </a></li>';
        content += '<li class="menu-item"><a href="electrical-circuit-breaker-operation-and-types-of-circuit-breaker/index.html">Electrical Circuit Breaker</a></li>';
        content += '<li class="menu-item"><a href="what-is-arc-arc-in-circuit-breaker/index.html">Arc in Circuit Breaker</a></li>';
        content += '<li class="menu-item"><a href="vacuum-arc-or-arc-in-vacuum/index.html">Vacuum Arc</a></li>';
        content += '<li class="menu-item"><a href="arc-interruption-theory/index.html">Arc Interruption Theory</a></li>';
        content += '<li class="menu-item"><a href="oil-circuit-breaker-bulk-and-minimum-oil-circuit-breaker/index.html">Oil Circuit Breaker</a></li>';
        content += '<li class="menu-item"><a href="air-circuit-breaker-air-blast-circuit-breaker/index.html">Air Circuit Breaker</a></li>';
        content += '<li class="menu-item"><a href="sulfur-hexafluoride-sf6-gas-properties/index.html">Sulphur Hexafluoride Gas Properties</a></li>';
        content += '<li class="menu-item"><a href="types-and-operation-of-sf6-circuit-breaker/index.html">SF6 Circuit Breaker</a></li>';
        content += '<li class="menu-item"><a href="vacuum-circuit-breaker-or-vcb-and-vacuum-interrupter/index.html">Vacuum Circuit Breaker</a></li>';
        content += '<li class="menu-item"><a href="working-principle-of-earth-leakage-circuit-breaker-elcb-voltage-current-elcb-rccb/index.html">Earth Leakage Circuit Breaker</a></li>';
        content += '<li class="menu-item"><a href="vacuum-switchgear/index.html">Vacuum Switchgear</a></li>';
        content += '<li class="menu-item"><a href="circuit-breaker-operation/index.html">Circuit Breaker Operation</a></li>';
        content += '<li class="menu-item"><a href="short-circuit-current-of-circuit-breaker/index.html">Short Circuit Current of Circuit Breaker</a></li>';
        content += '<li class="menu-item"><a href="gis-or-gas-insulated-switchgear/index.html">GIS or Gas Insulated Switchgear</a></li>';
        content += '<li class="menu-item"><a href="metal-enclosed-switchgear/index.html">Metal Enclosed Switchgear</a></li>';
        content += '<li class="menu-item"><a href="electrical-fuse-hrc-fuse-high-rupturing-capacity/index.html">Electrical Fuse</a></li>';
        content += '<li class="menu-item"><a href="miniature-circuit-breaker-or-mcb/index.html">Miniature Circuit Breaker</a></li>';
        content += '<li class="menu-item"><a href="low-voltage-switchgear/index.html">Low Voltage Switchgear</a></li>';
        content += '<li class="menu-item"><a href="medium-voltage-switchgear/index.html">Medium Voltage Switchgear</a></li>';
        content += '<li class="menu-item"><a href="high-voltage-switchgear/index.html">High Voltage Switchgear</a></li>';
        content += '<li class="menu-item"><a href="trip-circuit-supervision/index.html">Trip Circuit Supervision</a></li>';
        content += '<li class="menu-item"><a href="equipment-earthing/index.html">Equipment Earthing</a></li>';
        content += '<li class="menu-item"><a href="circuit-breaker-maintenance/index.html">Circuit Breaker Maintenance</a></li>';
        content += '<li class="menu-item"><a href="rating-of-circuit-breaker-short-circuit-breaking-making-current/index.html">Rating of Circuit Breaker</a></li>';
        content += '<li class="menu-item"><a href="high-voltage-testing/index.html">High Voltage Testing</a></li>';
        content += '<li class="menu-item"><a href="insulation-resistance-test-and-polarization-index-test/index.html">• <span class="subTopic">IR and PI Test</span></a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">PROTECTION</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="protection-system-in-power-system/index.html">Power System Protection</a></li>';
        content += '<li class="menu-item"><a href="types-of-electrical-protection-relays-or-protective-relays/index.html">Electrical Protection Relay</a></li>';
        content += '<li class="menu-item"><a href="pick-up-current-current-setting-plug-setting-multiplier-and-time-setting-multiplier-of-relay/index.html">Relay Setting Calculation</a></li>';
        content += '<li class="menu-item"><a href="code-of-practice-for-power-system-protection/index.html">Code of practice Electrical Protection</a></li>';
        content += '<li class="menu-item"><a href="vector-diagram-three-phase-vector-diagram/index.html">Three Phase Vector Diagram</a></li>';
        content += '<li class="menu-item"><a href="electrical-fault-calculation-positive-negative-zero-sequence-impedance/index.html">Electrical Fault Calculation</a></li>';
        content += '<li class="menu-item"><a href="electromagnetic-relay-working-types-of-electromagnetic-relays/index.html">Electromagnetic Relay</a></li>';
        content += '<li class="menu-item"><a href="working-principle-construction-and-types-of-induction-cup-relay/index.html">Induction Cup Type Relay</a></li>';
        content += '<li class="menu-item"><a href="over-current-relay-working-principle-types/index.html">Over Current Relay</a></li>';
        content += '<li class="menu-item"><a href="distance-relay-or-impedance-relay-working-principle-types/index.html">Distance Relay or Impedance Relay</a></li>';
        content += '<li class="menu-item"><a href="thermal-relay-working-principle-construction-of-thermal-overload-relay/index.html">Thermal Relay</a></li>'; 
        content += '<li class="menu-item"><a href="overvoltage-protection/index.html">Overvoltage Protection</a></li>';
        content += '<li class="menu-item"><a href="busbar-protection/index.html">Busbar Protection</a></li>';
        content += '<li class="menu-item"><a href="protection-of-lines-or-feeder/index.html">Feeder Protection</a></li>';
        content += '<li class="menu-item"><a href="surge-protection-and-lightning-arrester-surge-arrester/index.html">Surge Protection and Lightning Arrester</a></li>';
        content += '<li class="menu-item"><a href="protection-of-capacitor-bank/index.html">Capacitor Bank Protection</a></li>';
        content += '<li class="menu-item"><a href="transformer-protection-and-transformer-fault/index.html">Transformer Protection</a></li>';
        content += '<li class="menu-item"><a href="magnetizing-inrush-current-in-power-transformer/index.html">Inrush Current in Transformer</a></li>';
        content += '<li class="menu-item"><a href="small-large-motor-protection/index.html">Small and Large Motor Protection</a></li>';
        content += '<li class="menu-item"><a href="motor-thermal-overload-protection/index.html">Motor Thermal Overload Protection</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">MEASUREMENT</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="electrical-measuring-instruments-types-accuracy-precision-resolution-speed/index.html">Electrical Measuring Instruments</a></li>';
        content += '<li class="menu-item"><a href="errors-in-measurement-classification-of-errors/index.html">Errors in Measurement</a></li>';
        content += '<li class="menu-item"><a href="permanent-magnet-moving-coil-instrument/index.html">Permanent Magnet Moving Coil Instrument</a></li>';
        content += '<li class="menu-item"><a href="moving-iron-instrument/index.html">Moving Iron Instrument</a></li>';
        content += '<li class="menu-item"><a href="electrostatic-type-instruments-construction-principle-torque-equation/index.html">Electrostatic Type Instruments</a></li>';
        content += '<li class="menu-item"><a href="thermocouple-type-instruments-construction-principle-of-operation/index.html">Thermocouple Type Instruments</a></li>';
        content += '<li class="menu-item"><a href="rectifier-type-instrument-construction-principle-of-operation/index.html">Rectifier Type Instruments</a></li>';
        content += '<li class="menu-item"><a href="wheatstone-bridge-circuit-theory-and-principle/index.html">Wheatstone Bridge</a></li>';
        content += '<li class="menu-item"><a href="kelvin-bridge-circuit-kelvin-double-bridge/index.html">Kelvin Bridge</a></li>';
        content += '<li class="menu-item"><a href="maxwell-bridge-inductance-capacitance-bridge/index.html">Maxwell Bridge</a></li>';
        content += '<li class="menu-item"><a href="andersons-bridge/index.html">Anderson\'s Bridge</a></li>';
        content += '<li class="menu-item"><a href="hays-bridge-circuit-theory-phasor-diagram-advantages-applications/index.html">Hay\'s Bridge</a></li>';
        content += '<li class="menu-item"><a href="owens-bridge-circuit-and-advantages/index.html">Owen\'s Bridge</a></li>';
        content += '<li class="menu-item"><a href="schering-bridge-measurement-of-capacitance-using-schering-bridge/index.html">Schering Bridge</a></li>';
        content += '<li class="menu-item"><a href="heaviside-bridge/index.html">Heaviside Bridge</a></li>';
        content += '<li class="menu-item"><a href="de-sautys-bridge/index.html">De Sauty\'s Bridge</a></li>';
        content += '<li class="menu-item"><a href="temperature-sensor-types-of-temperature-sensor/index.html">Temperature Sensors and its types</a></li>';
        content += '<li class="menu-item"><a href="resistance-temperature-detector-or-rtd-construction-and-working-principle/index.html">Resistance Temperature Detector or RTD</a></li>';
        content += '<li class="menu-item"><a href="thermocouple-temperature-measurement/index.html">Thermocouple Temperature Measurement</a></li>';
        content += '<li class="menu-item"><a href="thermistor-thermometer-thermistor-temperature-sensor-construction-principle/index.html">Thermistor Thermometer</a></li>';
        content += '<li class="menu-item"><a href="radiation-pyrometer-types-working-principle/index.html">Radiation Pyrometer</a></li>';
        content += '<li class="menu-item"><a href="bimetallic-strip-thermometer/index.html">Bimetallic Strip Thermometer</a></li>';
        content += '<li class="menu-item"><a href="optical-pyrometer-construction-and-working-principle/index.html">Optical Pyrometer</a></li>';
        content += '<li class="menu-item"><a href="electrodynamometer-type-wattmeter/index.html">Electrodynamometer Type Wattmeter</a></li>';
        content += '<li class="menu-item"><a href="induction-type-meters/index.html">Induction Type Meters</a></li>';
        content += '<li class="menu-item"><a href="energy-meter-with-lag-adjustment-devices/index.html">Energy Meter with Lag Adjustment Devices</a></li>';
        content += '<li class="menu-item"><a href="what-is-low-power-factor-wattmeter/index.html">Low Power Factor Wattmeter</a></li>';
        content += '<li class="menu-item"><a href="potentiometer-working-principle-of-potentiometer/index.html">Working Principle of Potentiometer</a></li>';
        content += '<li class="menu-item"><a href="megger-working-principle-types-history-uses-of-megger/index.html">Megger</a></li>';
        content += '<li class="menu-item"><a href="power-factor-meters-electrodynamometer-type-power-factor-meter/index.html">Power Factor Meters</a></li>';
        content += '<li class="menu-item"><a href="varmeter-single-phase-and-polyphase-varmeter/index.html">Varmeter</a></li>';
        content += '<li class="menu-item"><a href="measurement-of-three-phase-power/index.html">Measurement of Three Phase Power</a></li>';
        content += '<li class="menu-item"><a href="weston-type-frequency-meter/index.html">Weston Type Frequency Meter</a></li>';
        content += '<li class="menu-item"><a href="phase-sequence-indicator/index.html">Phase Sequence Indicator</a></li>';
        content += '<li class="menu-item"><a href="blavier-test-murray-loop-test-varley-loop-test/index.html">Loop Tests</a></li>';
        content += '<li class="menu-item"><a href="cathode-ray-oscilloscope-cro/index.html">Cathode Ray Oscilloscope</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">CONTROL ENGINEERING</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="control-engineering-historical-review-and-types-of-control-engineering/index.html">Control Engineering</a></li>';
        content += '<li class="menu-item"><a href="on-off-control-theory-controller/index.html">On Off Control Theory and Controller</a></li>';
        content += '<li class="menu-item"><a href="control-system-closed-loop-open-loop-control-system/index.html">Closed and Open Loop Control System</a></li>';
        content += '<li class="menu-item"><a href="network-synthesis-hurwitz-polynomial-positive-real-functions/index.html">Theory of Network Synthesis</a></li>';
        content += '<li class="menu-item"><a href="types-of-systems-linear-and-non-linear-system/index.html">Types of Control System</a></li>';
        content += '<li class="menu-item"><a href="mathematical-modelling-of-various-system/index.html">Mathematical Modelling</a></li>';
        content += '<li class="menu-item"><a href="transient-state-and-steady-state-response-of-control-system/index.html">Steady State and Trainsient State Analysis</a></li>';
        content += '<li class="menu-item"><a href="root-locus-technique-in-control-system-root-locus-plot/index.html">Root Locus Technique</a></li>';
        content += '<li class="menu-item"><a href="bode-plot-gain-margin-phase-margin/index.html">Bode Plot</a></li>';
        content += '<li class="menu-item"><a href="types-of-controllers-proportional-integral-derivative-controllers/index.html">Types of Controllers</a></li>';
        content += '<li class="menu-item"><a href="compensation-in-control-system-lag-lead-compensation/index.html">Compensation in Control System</a></li>';
        content += '<li class="menu-item"><a href="state-space-analysis-of-control-system/index.html">State Space Analysis</a></li>';
        content += '<li class="menu-item"><a href="different-types-non-linearities-in-control-system/index.html">Non Linearities and Describing Function</a></li>';
        content += '<li class="menu-item"><a href="digital-data-control-system/index.html">Digital Data of Control System</a></li>';
        content += '<li class="menu-item"><a href="routh-hurwitz-stability-criterion/index.html">Routh Hurwitz Stability Criterion</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">ELECTRONIC DEVICES</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="theory-of-semiconductor/index.html">Theory of Semiconductor</a></li>';
        content += '<li class="menu-item"><a href="energy-brands-in-silicon/index.html">Energy Bands in Silicon</a></li>';
        content += '<li class="menu-item"><a href="intrinsic-silicon-and-extrinsic-silicon/index.html">Intrinsic Silicon and Extrinsic Silicon</a></li>';
        content += '<li class="menu-item"><a href="diode-working-principle-and-types-of-diode/index.html">Diode and types of Diode</a></li>';
        content += '<li class="menu-item"><a href="p-n-junction-diode/index.html">p-n Junction Diode</a></li>';
        content += '<li class="menu-item"><a href="diode-characteristics/index.html">Diode Characteristics</a></li>';
        content += '<li class="menu-item"><a href="jfet-or-junction-field-effect-transistor/index.html">Junction Field Effect Transistor</a></li>';
        content += '<li class="menu-item"><a href="mos-capacitor-mos-capacitance-c-v-curve/index.html">MOS Capacitor</a></li>';
        content += '<li class="menu-item"><a href="laser-types-and-components-of-laser/index.html">Types and Components of Laser</a></li>';
        content += '<li class="menu-item"><a href="half-wave-diode-rectifier/index.html">Half Wave Diode Rectifier</a></li>';
        content += '<li class="menu-item"><a href="full-wave-diode-rectifier/index.html">Full Wave Diode Rectifier</a></li>';
        content += '<li class="menu-item"><a href="zener-diode-symbol-and-application-as-voltage-regulator/index.html">Zener Diode</a></li>';
        content += '<li class="menu-item"><a href="bipolar-junction-transistor-or-bjt-n-p-n-or-p-n-p-transistor/index.html">Bipolar Junction Transistor or BJT</a></li>';
        content += '<li class="menu-item"><a href="biasing-of-bipolar-junction-transistor-bjt-or-bipolar-transistor-biasing/index.html">Biasing of BJT</a></li>';
        content += '<li class="menu-item"><a href="application-of-bipolar-junction-transistor-or-bjt-history-of-bjt/index.html">Application of BJT</a></li>';
        content += '<li class="menu-item"><a href="p-i-n-photodiode-avalanche-photo-diode/index.html">P-I-N Photodiode</a></li>';
        content += '<li class="menu-item"><a href="tunnel-diode/index.html">Tunnel Diode</a></li>';
        content += '<li class="menu-item"><a href="regulated-power-supply/index.html">Regulated Power Supply</a></li>';
        content += '<li class="menu-item"><a href="mosfet-working-principle-of-p-channel-n-channel-mosfet/index.html">MOSFET</a></li>';
        content += '<li class="menu-item"><a href="mosfet-circuits/index.html">MOSFET Circuits</a></li>';
        content += '<li class="menu-item"><a href="led-or-light-emitting-diode/index.html">LED or Light Emitting Diode</a></li>';
        content += '<li class="menu-item"><a href="variable-resistors/index.html">Variable Resistor</a></li>';
        content += '<li class="menu-item"><a href="varistor-metal-oxide-varistor-is-nonlinear-resistor/index.html">Varistor</a></li>';
        content += '<li class="menu-item"><a href="light-dependent-resistor-ldr-working-principle-of-ldr/index.html">Light Dependent Resistor</a></li>';
        content += '<li class="menu-item"><a href="amplifier-gain-decibel-or-db-gain/index.html">Amplifier Gain</a></li>';
        content += '<li class="menu-item"><a href="op-amp-working-principle-of-op-amp/index.html">Op-amp</a></li>';
        content += '<li class="menu-item"><a href="sensor-types-of-sensor/index.html">Sensor</a></li>';
        content += '<li class="menu-item"><a href="transducer-types-of-transducer/index.html">Transducer</a></li>';
        content += '<li class="menu-item"><a href="integrated-circuits-types-of-ic/index.html">Integrated Circuits</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">POWER ELECTRONICS</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="thyristor-silicon-controlled-rectifier/index.html">Thyristor</a></li>';
        content += '<li class="menu-item"><a href="characteristics-of-thyristor/index.html">Characteristics of Thyristor</a></li>';
        content += '<li class="menu-item"><a href="thyristor-triggering/index.html">Thyristor Triggering</a></li>';
        content += '<li class="menu-item"><a href="gate-characteristics-of-scr-or-thyristor/index.html">Gate Characteristics of SCR</a></li>';
        content += '<li class="menu-item"><a href="silicon-controlled-rectifier-scr-two-transistor-model-operating-principle/index.html">Silicon Controlled Rectifier</a></li>';
        content += '<li class="menu-item"><a href="rating-of-scr-or-thyristor/index.html">Rating of Thyristor or SCR</a></li>';
        content += '<li class="menu-item"><a href="switching-of-on-off-characteristics-of-scr-turn-on-turn-off-time/index.html">Switching On-Off Characteristic of Thyristor</a></li>';
        content += '<li class="menu-item"><a href="thyristor-protection-or-scr-protection/index.html">Thyristor or SCR Protection</a></li>';
        content += '<li class="menu-item"><a href="series-and-parallel-connection-of-scr-or-thyristor/index.html">Series and Parallel Connection of SCR</a></li>';
        content += '<li class="menu-item"><a href="chopper-dc-to-dc-converter/index.html">Chopper or DC to DC Converter</a></li>';
	content += '</ul>';
content += '</li>';
content += '<li class="sub menu-item"><a class="list"  href="#">DIGITAL ELECTRONICS</a>';
	content += '<ul class="sub-menu">';
        content += '<li class="menu-item"><a href="digital-electronics/index.html">Digital Electronics</a></li>';
        content += '<li class="menu-item"><a href="binary-number-system-binary-to-decimal-and-decimal-to-binary-conversion/index.html">Binary Number System</a></li>';
        content += '<li class="menu-item"><a href="binary-to-decimal-and-decimal-to-binary-conversion/index.html">Binary Decimal Conversion</a></li>';
        content += '<li class="menu-item"><a href="octal-to-decimal-and-decimal-to-octal-conversion/index.html">Octal Decimal Conversion</a></li>';
        content += '<li class="menu-item"><a href="hexadecimal-to-decimal-and-decimal-to-hexadecimal-conversion/index.html">Hexadecimal Decimal Conversion</a></li>';
        content += '<li class="menu-item"><a href="binary-to-octal-and-octal-to-binary-conversion/index.html">Binary Octal Conversion</a></li>';
        content += '<li class="menu-item"><a href="binary-to-hexadecimal-and-hex-to-binary-conversion/index.html">Binary Hexadecimal Conversion</a></li>';
        content += '<li class="menu-item"><a href="binary-arithmetic/index.html">Binary Arithmetic</a></li>';
        content += '<li class="menu-item"><a href="binary-addition/index.html">Binary Addition</a></li>';
        content += '<li class="menu-item"><a href="binary-subtraction/index.html">Binary Subtraction</a></li>';
        content += '<li class="menu-item"><a href="binary-multiplication/index.html">Binary Multiplication</a></li>';
        content += '<li class="menu-item"><a href="binary-division/index.html">Binary Division</a></li>';
        content += '<li class="menu-item"><a href="bcd-or-binary-coded-decimal-bcd-conversion-addition-subtraction/index.html">Binary Coded Decimal</a></li>';
        content += '<li class="menu-item"><a href="gray-code-binary-to-gray-code-and-that-to-binary-conversion/index.html">Gray Code</a></li>';
        content += '<li class="menu-item"><a href="alphanumeric-codes-ascii-code-ebcdic-code-unicode/index.html">Alphanumeric codes</a></li>';
        content += '<li class="menu-item"><a href="1s-complement/index.html">1s Complement</a></li>';
        content += '<li class="menu-item"><a href="2s-complement/index.html">2s Complement</a></li>';
        content += '<li class="menu-item"><a href="hamming-code/index.html">Hamming Code</a></li>';
        content += '<li class="menu-item"><a href="9s-complement-and-10s-complement/index.html">9s and 10s Complement</a></li>';
        content += '<li class="menu-item"><a href="de-morgans-theorem-and-demorgans-laws/index.html">De Morgan\'s Theorem</a></li>';
        content += '<li class="menu-item"><a href="or-operation-logical-or-operation/index.html">Logical OR Operation</a></li>';
        content += '<li class="menu-item"><a href="and-operation-logical-and-operation/index.html">Logical AND Operation</a></li>';
        content += '<li class="menu-item"><a href="truth-table/index.html">Truth Table</a></li>';
        content += '<li class="menu-item"><a href="logical-or-gate/index.html">Logical OR Gate</a></li>';
        content += '<li class="menu-item"><a href="exclusive-or-gate/index.html">Exclusive OR Gate</a></li>';
        content += '<li class="menu-item"><a href="logical-and-gate/index.html">Logical AND Gate</a></li>';
        content += '<li class="menu-item"><a href="nand-gate/index.html">NAND Gate</a></li>';
        content += '<li class="menu-item"><a href="not-gate/index.html">NOT Gate</a></li>';
        content += '<li class="menu-item"><a href="boolean-algebra-theorems-and-laws-of-boolean-algebra/index.html">Boolean Algebra</a></li>';
        content += '<li class="menu-item"><a href="excess-3-code/index.html">Excess 3 code Addition & Subtraction</a></li>';
        content += '<li class="menu-item"><a href="error-detection-and-correction-codes/index.html">Error Detection and Correction Codes</a></li>';
        content += '<li class="menu-item"><a href="inhibit-gate/index.html">INHIBIT Gate</a></li>';
        content += '<li class="menu-item"><a href="logic-families-significant-and-types/index.html">Logic Families Significant</a></li>';
        content += '<li class="menu-item"><a href="ascii-code/index.html">ASCII Code</a></li>';
        content += '<li class="menu-item"><a href="universal-gate-nand-nor-gate-as-universal-gate/index.html">Universal Gate</a></li>';
        content += '<li class="menu-item"><a href="nmos-and-pmos-logic/index.html">NMOS and PMOS Logic</a></li>';
        content += '<li class="menu-item"><a href="schmitt-gates/index.html">Schmitt Gates</a></li>';
        content += '<li class="menu-item"><a href="seven-segment-display/index.html">Seven Segment Display</a></li>';
        content += '<li class="menu-item"><a href="transistor-transistor-logic-or-ttl/index.html">Transistor Transistor Logic or TTL</a></li>';
        content += '<li class="menu-item"><a href="fan-out-of-logic-gates/index.html">Fan out of Logic Gates</a></li>';
        content += '<li class="menu-item"><a href="some-common-applications-of-logic-gates/index.html">Applications of Logic Gates</a></li>';
	content += '</ul>';
content += '</li>';
content += '</ul>';
$(content).appendTo("#menu");

$(".list").parents('li').find("ul").hide();

$(".list").click( function(event)
{
   if($(this).parents('li').find("ul").is(':visible'))
	{
		$(this).parents('li').find("ul").hide();
	}
	else
	{
		$(this).parents('li').find("ul").show();
	}
  	//$(this).parents('li').find("ul").hide();
});
	});

(function ($) {
		  // custom css expression for a case-insensitive contains()
		  jQuery.expr[':'].Contains = function(a,i,m){
			  return (a.textContent || a.innerText || "").toUpperCase().indexOf(m[3].toUpperCase())>=0;
		  };
		
		
		  function listFilter(input) { // list is an unordered list
			
			$(input)
			  .change( function () {
				var filter = $(this).val();
				if(filter) {
				  // this finds all links in a list that contain the input,
				  // and hide the ones not containing the input while showing the ones that do
				  $(".sub-menu").show();
				  $(".sub-menu").find("a:not(:Contains(" + filter + "))").slideUp();
				  $(".sub-menu").find("a:Contains(" + filter + ")").slideDown();
				  $(".list").slideUp()
				  
				} else {
				  $(list).find("li").slideDown();
				}
				return false;
			  })
			  
			.keypress( function () {
				// fire the above change event after every letter
				if (window.event.keyCode == 13)
				{
					$(this).change();
				}
				
			});
		  }
		
		  //ondomready
		  $(function () {
			var input = $("#input");	
			listFilter(input);
		  });
		   }(jQuery));

